# Generated by Django 3.1.5 on 2021-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='products',
        ),
        migrations.AddField(
            model_name='receipt',
            name='products',
            field=models.CharField(default='', max_length=255),
        ),
    ]
